ng build --prod failed with error "ERROR in src/app/layout/content/journal/document/components/one/journal.one.document.component.html(22,37): : Property 'updateTime' does not exist on type 'JournalDocumentModel'."